# This workflow generates the THIRD-PARTY file and creates a PR from the changes.
# For more information see: https://github.com/marketplace/actions/create-pull-request

name: Third Party Generate

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Checkout Data-Prepper
      uses: actions/checkout@v2
    - name: Generate Third Party Report
      run: ./gradlew --no-daemon generateThirdPartyReport
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.0.4
      with:
        add-paths: THIRD-PARTY
        commit-message: 'Generated THIRD-PARTY file'
        signoff: true
        branch: generate-${{ github.run_number }}
        delete-branch: true
        title: 'Generated THIRD-PARTY file'
        body: |
          Generated `THIRD-PARTY` file with:

          ```
          ./gradlew generateThirdPartyReport
          ```
